---
title: "GSE74927_bulk"
output: html_document
---

## Librerias necesarias  ####
require(DESeq2)
require(ggplot2)
require(corrplot)
library(tidyverse)
library(apeglm)
library(vsn)
library(readr)
#### Librerias para el análisis cluster 
library(GEOquery)
library(ggplot2)
require(DESeq2)
require(ggplot2)
require(corrplot)
library(apeglm)
library(ade4)
library(vsn)
library(viridis)
library(readxl)
library(GEOquery)
library(limma)
library(umap)
### Librerias para redes de coexpresion 
library(affy) #Funciones para el análisis exploratorio de datos de microarreglos (oligonucleótidos).
library(siggenes) #Identificación de genes expresados diferencialmente por el método SAM (Significance Analysis of Microarrays)
library(minet) #Inferencia de RCG usando información mutua.
library(igraph) #Análisis y manipulación de redes
library(infotheo)#del CRAN
library(oligo)
library(GEOquery)
library(limma)
library(umap)
library(corrplot)
library(Matrix)
library(genefilter)
### Librerias para el enriquecimiento
library(org.Hs.eg.db)
install.packages("remotes")
remotes::install_github("YuLab-SMU/clusterProfiler")
library(clusterProfiler)
library(enrichplot)
library(pathview)
## Carga de los datos #2###
Tabla927 <- read.delim("PROYECTO/GSE927/GSE74927_all_sample_raw_count.txt")
#view(Tabla927)
dim(Tabla927)
## Cambio de nombre y reorganización de la tabla ####
rownames(Tabla927)<- Tabla927$symbol
colnames(Tabla927)<- c("GEN","Negativo1" ,"Positivo1" ,"Positivo2", "Negativo2", "Positivo3", "Positivo4", "Positivo5", "Positivo6",
                        "Negativo3", "Negativo4", "Negativo5", "Negativo6", "Positivo7", "Negativo7", "Negativo8", "Positivo8", "Negativo9",
                        "Negativo10", "Positivo9", "Positivo10", "Positivo11", "Negativo11", "Positivo12", "Negativo12", "Negativo13", "Positivo13",
                        "Negativo14","Positivo14", "Positivo15", "Positivo16", "Positivo17", "Negativo15", "Negativo16", "Negativo17", "Negativo18",
                        "Positivo18") 
tabla927neg<-paste0("Negativo",1:18)
tabla927pos<-paste0("Positivo", 1:18)
tabla927neg<-Tabla927[tabla927neg]
tabla927pos<-Tabla927[tabla927pos]
Tabla927<-cbind(tabla927neg,tabla927pos)
## Algunos filtros necesarios ####

#Filtro de ceros

Tabla927_2<-Tabla927[rowSums(Tabla927)!=0,]
dim(Tabla927)
dim(Tabla927_2) ## Se redujeron un total de 23367-20847 = 2520 valores.

##Filtro por varianza pequeña
Tabla927_3<-Tabla927_2[0<apply(Tabla927_2,1,var),] #No es necesario eliminar por varianza pequeña
dim(Tabla927_2)
dim(Tabla927_3)
##Filtro por lecturas muy grandes 
Tabla927_4=Tabla927_3[4000>apply(Tabla927_3,1,max),]
dim(Tabla927_3)
dim(Tabla927_4) #Se redujeron 20847-15416= 5431 valores por valores muy grandes
Tabla927<-Tabla927_4 ## Renombrando la tabla final filtrada.
### Primer Boxplot #######
boxplot(Tabla927, boxwex=0.7, notch=T, outline=FALSE, las=2,col = cm.colors(10),
        main="Boxplot datos originales.",ylab="Conteos")
corrplot(cor(Tabla927))
### Creacion de la tabla para DEseq2 ####
coldata1 <- data.frame(condition=factor(c(rep('Negativo',18),rep('Positivo',18))))
rownames(coldata1) = colnames(Tabla927)
coldata1$condition <- relevel(coldata1$condition, ref='Negativo')#Condición control
coldata1
###Modelado utilizando Deseq2 ###
Tabla927_rnaseq <- DESeqDataSetFromMatrix(
  countData =Tabla927,
  colData = coldata1,
  design= ~ condition)
##Normalización ####
#No se elimina ninguna muestra puesto que ningún sizefactor es mayor que 3 ni menor que 0.3
Tabla927_rnaseq <- estimateSizeFactors(Tabla927_rnaseq)
sizeFactors(Tabla927_rnaseq)
head(counts(Tabla927_rnaseq,normalized=TRUE))
boxplot(counts(Tabla927_rnaseq,normalized=TRUE), boxwex=0.7, notch=T, outline=FALSE, las=2,col = cm.colors(10),
        main="Boxplot datos Normalizados.",ylab="Conteos")
norm_dseq<-counts(Tabla927_rnaseq,normalized=TRUE)
corrplot.mixed(cor(norm_dseq))
#### Obteniendo los DEGs primera base de datos RNAseq####
##test de Wald
Tabla927_rnaseq <- DESeq(Tabla927_rnaseq, test="Wald")
res0_rnaseq <- results(Tabla927_rnaseq)
resOrder_rnaseq <- Tabla927_rnaseq[order(res0_rnaseq$padj), ]
dim(res0_rnaseq)
dim(resOrder_rnaseq)
#write.csv(as.data.frame(resOrder),file="valores_p.csv")
##Valores p ajustados 
# Filtrar res0_rnaseq por la condición y almacenar los resultados en filtered_res
filtered_res <- res0_rnaseq[complete.cases(res0_rnaseq) & res0_rnaseq$padj < 0.001, ]
# Crear el nuevo DataFrame con la columna 'p' y mantener los nombres de fila originales
Padj0_rnaseq <- data.frame(p = filtered_res$padj, row.names = rownames(filtered_res))
res0_rna <- data.frame(LFC = filtered_res$log2FoldChange, row.names = rownames(filtered_res2))
dim(Padj0_rnaseq)#Se tienen 1795  DEGS
Padj0_rnaseq <- na.omit(Padj0_rnaseq)
#res0_rna=data.frame(lfc=res0_rnaseq$log2FoldChange[res0_rnaseq$padj<0.001])
res0_rna <- na.omit(res0_rna)
dim(Padj0_rnaseq)## Se tienen 1795 DEGS sin NA.
dim(res0_rna)
#write.csv(as.data.frame(Padj0_rnaseq), file="Padj_927.csv")
### Gráfico sdvs mean y MA-plot (Luego de Normalizar)######
plotDispEsts(Tabla927_rnaseq,xlab="Media de los conteos normalizados",ylab="Dispersión",main="Gráfico sd vs media") # estimaciones dispersiones
plotMA(res0_rnaseq,xlab="Media de los conteos normalizados",main="Gráfico MA") #(LL) ¿Para realizar este gráfico que valores se le deben ingresar?
## Redes de coexpresión #######
#E1_927<-Tabla927[as.numeric(rownames(Padj0_rnaseq)),]## Guardando la base de datos solo con los DEGS.
dim(E1_927)

Lista_927 <- cbind(Padj0_rnaseq, res0_rna)
write.csv(as.data.frame(Lista_927), file="Lista_927.csv")


####################ENRIQUECIMIENTO##############################################333

DE_genes <- c(rownames(Padj0_rnaseq))

# Realizar el análisis de enriquecimiento funcional utilizando la base de datos GO
enrichGO <- enrichGO(gene          = DE_genes,
                     OrgDb         = org.Hs.eg.db,
                     keyType       = "SYMBOL",  # Cambiar a "SYMBOL" si tus genes están representados por su símbolo de gen
                     ont           = "BP",
                     pAdjustMethod = "fdr",     # Otros métodos de ajuste: "none", "holm", "hochberg", "hommel", "bonferroni", "BH", "BY", "fdr"
                     pvalueCutoff  = 1,      # Cambiar a "pvalueCutoff" si prefieres usar un valor de corte para los valores de p sin ajustar
                     qvalueCutoff  = 0.05,
                     readable      = TRUE)



head(enrichGO)
barplot(enrichGO)
dotplot(enrichGO)
cnetplot(enrichGO)

pathview(gene.data = DE_genes, species = "hsa", pathway.id = "hsa05200", file.out = "pathway_visualization.pdf")


enrichGO_CC <- enrichGO(gene          = DE_genes,
                        OrgDb         = org.Hs.eg.db,
                        keyType       = "SYMBOL",
                        ont           = "CC",
                        pAdjustMethod = "fdr",     
                        pvalueCutoff  = 0.05,     
                        qvalueCutoff  = 0.05,
                        readable      = TRUE)

head(enrichGO_CC)
barplot(enrichGO_CC)
dotplot(enrichGO_CC)
cnetplot(enrichGO_CC)

enrichGO_MF <- enrichGO(gene          = DE_genes,
                        OrgDb         = org.Hs.eg.db,
                        keyType       = "SYMBOL", 
                        ont           = "MF",
                        pAdjustMethod = "fdr",     
                        pvalueCutoff  = 1,      
                        qvalueCutoff  = 0.05,
                        readable      = TRUE)
head(enrichGO_MF)
barplot(enrichGO_MF)
dotplot(enrichGO_MF)
cnetplot(enrichGO_MF)